version: "3.8"

networks:
  kafkanetwork:
    driver: bridge

services:

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6.2
    hostname: zookeeper
    volumes:
      - /docker-data/zookeeper-data:/data
      - /docker-data/zookeeper-datalog:/datalog
    ports:
      - "2181:2181"
    networks:
      - kafkanetwork

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092:9092"
    hostname: kafka1
    networks:
      - kafkanetwork
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.100.13
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
 #     ALLOW_PLAINTEXT_LISTENERS: yes
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker-data/kafka1:/var/lib/kafka/data

  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9093:9092"
    hostname: kafka2
    networks:
      - kafkanetwork
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.100.13
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_ADVERTISED_PORT: 9093
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9093
#      ALLOW_PLAINTEXT_LISTENERS: yes
    depends_on:
      - kafka1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker-data/kafka2:/var/lib/kafka/data

  kafka3:
    container_name: kafka3
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9094:9092"
    hostname: kafka3
    networks:
      - kafkanetwork
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.100.13
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_ADVERTISED_PORT: 9094
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9094
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9094
 #     ALLOW_PLAINTEXT_LISTENERS: yes
    depends_on:
      - kafka2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker-data/kafka3:/var/lib/kafka/data


   
